### ISSUE TITLE
Unable to sign in via Google.  (Didn't use docker since it's a existing project)

### ISSUE THREAD

**Issue by NLStom** [ghoshnirmalya/nextjs-authentication-using-strapi-and-next-auth#1]
[next-auth][error][adapter_connection_error]
https://next-auth.js.org/er... error: role "strapi" does not exist

I got an error to sign in with Try signing with a different account.

[next-auth][error][oauth_callback_handler_error] 
https://next-auth.js.org/errors#oauth_callback_handler_error TypeError: Cannot destructure property `manager` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/cli/Documents/react/shop-flish-frontend/node_modules/next-auth/dist/adapters/typeorm/index.js:111:11)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/cli/Documents/react/shop-flish-frontend/node_modules/next-auth/dist/adapters/typeorm/index.js:26:103)
    at _next (/Users/cli/Documents/react/shop-flish-frontend/node_modules/next-auth/dist/adapters/typeorm/index.js:28:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[next-auth][error][adapter_connection_error] 
https://next-auth.js.org/errors#adapter_connection_error error: role "strapi" does not exist
    at Parser.parseErrorMessage (/Users/cli/Documents/react/shop-flish-frontend/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/cli/Documents/react/shop-flish-frontend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/cli/Documents/react/shop-flish-frontend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/cli/Documents/react/shop-flish-frontend/node_modules/pg-protocol/dist/index.js:10:42)

**Comment by ghoshnirmalya** [comment]
@NLStom  I believe that this issue is similar to https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate/issues/4. Please let me know if the discussion in that issue helps you. I'll keep this open for the time being.

**Comment by NLStom** [comment]
Thank you for pointing me to the right direction.
